# -*- coding: utf-8 -*-
"""Prak3_elkom 1 dan elkom 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBPq8e5xvSjF0zTHgTzXe4BBslYKK3C9
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')


angka_awal = int(input("Masukkan angka awal: "))
angka_akhir = int(input("Masukkan angka akhir: "))

awal = angka_awal
akhir = angka_akhir

while awal <= akhir:
    print(awal, "|", akhir)
    awal = awal + 1
    akhir = akhir - 1

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
# Mendefinisikan nilai-nilai nominal uang lembar
uang_lembar = [100000, 50000, 20000, 10000, 5000, 2000, 1000]

# Meminta input total harga belanjaan dan jumlah uang
total_harga = int(input("Masukkan total harga belanjaan: "))
jumlah_uang = int(input("Masukkan jumlah uang yang diberikan: "))

# Menghitung kembalian
kembalian = jumlah_uang - total_harga

# Menampilkan kembalian
print("Kembalian Anda adalah:", kembalian)

# Mengidentifikasi besaran uang lembar dari kembalian
print("Besaran uang lembar yang diberikan sebagai kembalian:")
for lembar in uang_lembar:
    if kembalian >= lembar:
        jumlah_lembar = kembalian // lembar
        kembalian %= lembar
        print(f"{jumlah_lembar} lembar x {lembar} IDR")